services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - scooter-network 

  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    volumes:
      - ./osrm-data:/data
    command: >
      osrm-routed
      --algorithm mld
      /data/sweden-latest.osrm
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - scooter-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongo
    restart: unless-stopped
    command: > 
      sh -c "node server.js"
    networks:
      - scooter-network
  backend-test:
    build: ./backend
    profiles:
      - test
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    depends_on:
      - mongo
    command: "npm run test"
    environment:
      - NODE_ENV=test
      - MONGO_URI=mongodb://mongo:27017/test
    networks:
      - scooter-network

  admin-webb:
    build: ./admin-webb
    ports:
      - "8081:80"
    depends_on:
      - backend
    env_file:
      - ./.env
    environment:
      VITE_API_BASE: http://localhost:3000
    restart: unless-stopped
    networks:
      - scooter-network

  user-webb:
    build: ./user-webb
    ports:
      - "8080:80"
    depends_on:
      - backend
    env_file:
      - ./.env
    environment:
      BASE_API_URL: http://backend:3000
    restart: unless-stopped

  user-mobile:
    build: ./user-mobile
    ports:
      - "8082:80"
    depends_on:
      - backend
    env_file:
      - ./.env
    environment:
      BASE_API_URL: http://backend:3000
    restart: unless-stopped

  bike:
    build: ./bike
    depends_on:
      - backend
      - osrm
    environment:
      BASE_API_URL: http://backend:3000
    env_file:
      - ./.env
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - scooter-network

networks:
  scooter-network:
    driver: bridge

volumes:
  mongo-data:
